ALTER TABLE web_users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS verification_code VARCHAR(6);
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS requests_standard INTEGER DEFAULT 3;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS requests_pro INTEGER DEFAULT 0;
ALTER TABLE web_users ADD COLUMN IF NOT EXISTS requests_max INTEGER DEFAULT 0;